Update apigee-proxy-deploy.yaml

diff --git a/.github/workflows/apigee-proxy-deploy.yaml b/.github/workflows/apigee-proxy-deploy.yaml
--- a/.github/workflows/apigee-proxy-deploy.yaml
+++ b/.github/workflows/apigee-proxy-deploy.yaml
@@ -25,26 +25,26 @@ jobs:
            echo "Failed to get latest release version"
            exit 1
            fi
-    echo "Latest release: $LATEST_RELEASE"
+           echo "Latest release: $LATEST_RELEASE"
     
            DOWNLOAD_URL="https://github.com/apigee/apigeecli/releases/download/${LATEST_RELEASE}/apigeecli-linux-amd64"
-    echo "Downloading from: $DOWNLOAD_URL"
+           echo "Downloading from: $DOWNLOAD_URL"
     
-          if curl -L -o apigeecli "$DOWNLOAD_URL"; then
-      chmod +x apigeecli
-      sudo mv apigeecli /usr/local/bin/
-      if apigeecli version; then
-        echo "apigeecli installed successfully"
-      else
-        echo "apigeecli installation failed"
-        exit 1
-      fi
-         else
-      echo "Failed to download apigeecli"
-      exit 1
-     fi
+           if curl -L -o apigeecli "$DOWNLOAD_URL"; then
+           chmod +x apigeecli
+           sudo mv apigeecli /usr/local/bin/
+           if apigeecli version; then
+           echo "apigeecli installed successfully"
+           else
+           echo "apigeecli installation failed"
+           exit 1
+           fi
+           else
+           echo "Failed to download apigeecli"
+           exit 1
+           fi
     
-     - name: Set up gcloud CLI
+    - name: Set up gcloud CLI
       uses: google-github-actions/setup-gcloud@v0.2.0
       with:
         service_account_key: ${{ secrets.GCP_CREDENTIALS }}
